FROM alpine:3.14
RUN apk update
RUN apk add git
RUN apk add curl
RUN apk add gradle
RUN apk add openjdk-8
RUN apk add terraform
RUN apk add python py2-pip
RUN pip install cffi
RUN pip install ansible 